#!/usr/bin/env bash
set -Eeuo pipefail

readonly INSTALL_CONFIG=/etc/ssh-tunnel/install.conf

usage() {
    cat <<'EOF'
Usage: sudo ssh-tunnel-add-client-key [--label LABEL] PUBLIC_KEY_FILE
       cat key.pub | sudo ssh-tunnel-add-client-key [--label LABEL] -

Adds one or more public keys to the dedicated forwarding-only SSH endpoint.
Duplicate key material is ignored even when comments differ.
EOF
}

die() {
    printf 'ssh-tunnel-add-client-key: %s\n' "$*" >&2
    exit 1
}

label=
while (( $# )); do
    case $1 in
        --label)
            (( $# >= 2 )) || die "--label requires a value"
            label=$2
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        -*)
            [[ $1 == - ]] && break
            die "unknown option: $1"
            ;;
        *)
            break
            ;;
    esac
done

(( EUID == 0 )) || die "run as root"
(( $# == 1 )) || { usage >&2; exit 2; }
[[ -z "$label" || "$label" =~ ^[A-Za-z0-9][A-Za-z0-9_.@-]*$ ]] ||
    die "invalid label"
[[ -r "$INSTALL_CONFIG" ]] || die "$INSTALL_CONFIG is missing; run gateway/deploy.sh first"

# Generated by deploy.sh from validated values.
# shellcheck disable=SC1090
source "$INSTALL_CONFIG"
: "${TUNNEL_USER:?missing TUNNEL_USER in $INSTALL_CONFIG}"
: "${AUTHORIZED_KEYS_FILE:?missing AUTHORIZED_KEYS_FILE in $INSTALL_CONFIG}"
tunnel_group=$(id -gn "$TUNNEL_USER") || die "cannot resolve group for $TUNNEL_USER"

key_source=$1
if [[ $key_source == - ]]; then
    key_source=/dev/stdin
elif [[ ! -r $key_source ]]; then
    die "cannot read public key file: $key_source"
fi

install -d -o root -g root -m 0755 "$(dirname "$AUTHORIZED_KEYS_FILE")"
touch "$AUTHORIZED_KEYS_FILE"
chown root:"$tunnel_group" "$AUTHORIZED_KEYS_FILE"
chmod 0640 "$AUTHORIZED_KEYS_FILE"

validation_file=$(mktemp)
trap 'rm -f -- "$validation_file"' EXIT
added=0

while IFS= read -r public_key || [[ -n $public_key ]]; do
    [[ -z $public_key || $public_key == \#* ]] && continue
    read -r key_type key_data key_comment <<<"$public_key"
    [[ -n ${key_type:-} && -n ${key_data:-} ]] || die "input contains an invalid public key"
    normalised="$key_type $key_data ${label:-${key_comment:-ssh-tunnel-client}}"
    printf '%s\n' "$normalised" >"$validation_file"
    fingerprint=$(ssh-keygen -l -E sha256 -f "$validation_file" 2>/dev/null) ||
        die "input contains an invalid OpenSSH public key"
    if awk -v key_data="$key_data" '
        {
            for (field = 1; field <= NF; field++) {
                if ($field == key_data) found = 1
            }
        }
        END { exit !found }
    ' "$AUTHORIZED_KEYS_FILE"; then
        printf 'Already present: %s\n' "$fingerprint"
        continue
    fi
    printf '%s\n' "$normalised" >>"$AUTHORIZED_KEYS_FILE"
    printf 'Added: %s\n' "$fingerprint"
    ((added += 1))
done <"$key_source"

printf 'Added keys: %d\n' "$added"
