#!/usr/bin/env bash
set -Eeuo pipefail

purge=0
confirmed=0

usage() {
    cat <<'EOF'
Usage: sudo ./server/gateway/uninstall.sh --yes [--purge]

Removes installed services and program files. Configuration, host keys,
authorized client keys and the tunnel account are preserved by default.

  --purge  Also remove /etc/ssh-tunnel, /var/lib/ssh-tunnel and account
  --yes    Required confirmation
EOF
}

while (( $# )); do
    case $1 in
        --purge) purge=1 ;;
        --yes) confirmed=1 ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown option: %s\n' "$1" >&2; exit 2 ;;
    esac
    shift
done

(( EUID == 0 )) || { printf 'Run as root.\n' >&2; exit 1; }
(( confirmed )) || { printf 'Refusing without --yes.\n' >&2; exit 1; }

tunnel_user=ssh-tun
user_created=0
if [[ -r /etc/ssh-tunnel/install.conf ]]; then
    # Generated by gateway/deploy.sh from a validated account name.
    # shellcheck disable=SC1091
    source /etc/ssh-tunnel/install.conf
    tunnel_user=${TUNNEL_USER:-$tunnel_user}
    user_created=${USER_CREATED:-0}
fi

systemctl disable --now ssh-tunnel-sshd.service ssh-tunnel-socks.service 2>/dev/null || true
rm -f -- \
    /etc/systemd/system/ssh-tunnel-sshd.service \
    /etc/systemd/system/ssh-tunnel-socks.service \
    /usr/local/sbin/ssh-tunnel-add-client-key \
    /usr/local/sbin/ssh-tunnel-remove-client-key
rm -rf -- /usr/local/libexec/ssh-tunnel
systemctl daemon-reload

if (( purge )); then
    rm -rf -- /etc/ssh-tunnel /var/lib/ssh-tunnel
    if [[ "$user_created" == 1 ]] && id "$tunnel_user" >/dev/null 2>&1; then
        userdel "$tunnel_user"
    fi
    if [[ "$user_created" == 1 ]]; then
        printf 'Removed services, program files, configuration, keys and account.\n'
    else
        printf 'Removed services, program files, configuration and keys; preserved pre-existing account %s.\n' "$tunnel_user"
    fi
else
    printf 'Removed services and program files. Preserved:\n'
    printf '  /etc/ssh-tunnel\n  /var/lib/ssh-tunnel\n  account %s\n' "$tunnel_user"
fi
